name: classico # Changed from final_project for clarity
description: "A social app for train travelers." # Updated description
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3  # For better image loading
  intl: ^0.18.1  # For date formatting
  cupertino_icons: ^1.0.8
  # Dependencies for Train Social App
  firebase_core: ^3.12.1
  firebase_database: ^11.3.1
  url_launcher: ^6.1.14
  geolocator: ^10.1.0
  flutter_local_notifications: ^18.0.1
  cloud_firestore: ^5.6.5
  dropdown_button2: ^2.3.9
  http: ^1.3.0
  firebase_auth: ^5.0.0
  # google_maps_flutter: ^2.5.3 #If you plan to show maps
  # shared_preferences: ^2.2.2 #For local data storage
  # intl: ^0.19.0 #For date and time formatting
  # provider: ^6.1.1 #If using Provider for state management
  # cached_network_image: ^3.3.1 # For caching images from the network.
  # flutter_local_notifications: ^16.3.3 #To show notifications
  # permission_handler: ^11.1.0 # To handle runtime permissions.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets, uncomment this section.
  assets:
    - assets/images/ #Make sure you have this folder in your project
#     - assets/icons/  #Make sure you have this folder in your project
#     - assets/images/train_icon.png
