// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBScYxzytUVaO15S9zxZPZk3Em0AEUL3HM',
    appId: '1:805459104870:web:2b7241e089b0fd92e789a7',
    messagingSenderId: '805459104870',
    projectId: 'classico-dc2a9',
    authDomain: 'classico-dc2a9.firebaseapp.com',
    storageBucket: 'classico-dc2a9.firebasestorage.app',
    measurementId: 'G-4207C9MC24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtmky3Q3BiPWjYordKGs7cm9Fqp1PCkmE',
    appId: '1:805459104870:android:92393ece148dc966e789a7',
    messagingSenderId: '805459104870',
    projectId: 'classico-dc2a9',
    storageBucket: 'classico-dc2a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-DRGRCfLd3AD3PQoMaLFRuWuQZWKnKnI',
    appId: '1:805459104870:ios:048d6627869a2002e789a7',
    messagingSenderId: '805459104870',
    projectId: 'classico-dc2a9',
    storageBucket: 'classico-dc2a9.firebasestorage.app',
    iosBundleId: 'com.example.classico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-DRGRCfLd3AD3PQoMaLFRuWuQZWKnKnI',
    appId: '1:805459104870:ios:048d6627869a2002e789a7',
    messagingSenderId: '805459104870',
    projectId: 'classico-dc2a9',
    storageBucket: 'classico-dc2a9.firebasestorage.app',
    iosBundleId: 'com.example.classico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBScYxzytUVaO15S9zxZPZk3Em0AEUL3HM',
    appId: '1:805459104870:web:10e00f795336afc6e789a7',
    messagingSenderId: '805459104870',
    projectId: 'classico-dc2a9',
    authDomain: 'classico-dc2a9.firebaseapp.com',
    storageBucket: 'classico-dc2a9.firebasestorage.app',
    measurementId: 'G-MZ5D4WG402',
  );

}