// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDexBxTK3DcjskLPaeGpBStggUkMi_ZtjI',
    appId: '1:50731714956:web:0981aedbc336e857042ea9',
    messagingSenderId: '50731714956',
    projectId: 'classico-10cae',
    authDomain: 'classico-10cae.firebaseapp.com',
    storageBucket: 'classico-10cae.firebasestorage.app',
    measurementId: 'G-B9REZVNY9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdKJKcdtAHJZxMpucDMILN1m-Y2iexp5c',
    appId: '1:50731714956:android:7f105a82b94ef91d042ea9',
    messagingSenderId: '50731714956',
    projectId: 'classico-10cae',
    storageBucket: 'classico-10cae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTxrjk7a88v-QPjplAtRTYIAvonFOHGyc',
    appId: '1:50731714956:ios:24ee66b38886aa33042ea9',
    messagingSenderId: '50731714956',
    projectId: 'classico-10cae',
    storageBucket: 'classico-10cae.firebasestorage.app',
    iosBundleId: 'com.example.classico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTxrjk7a88v-QPjplAtRTYIAvonFOHGyc',
    appId: '1:50731714956:ios:24ee66b38886aa33042ea9',
    messagingSenderId: '50731714956',
    projectId: 'classico-10cae',
    storageBucket: 'classico-10cae.firebasestorage.app',
    iosBundleId: 'com.example.classico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDexBxTK3DcjskLPaeGpBStggUkMi_ZtjI',
    appId: '1:50731714956:web:ade1a1ab19d53fbc042ea9',
    messagingSenderId: '50731714956',
    projectId: 'classico-10cae',
    authDomain: 'classico-10cae.firebaseapp.com',
    storageBucket: 'classico-10cae.firebasestorage.app',
    measurementId: 'G-8TMLB7QXF4',
  );
}
